# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/mlopsnotes',
                'doc_host': 'https://thigm85.github.io',
                'git_url': 'https://github.com/thigm85/mlopsnotes',
                'lib_path': 'mlopsnotes'},
  'syms': { 'mlopsnotes.core': { 'mlopsnotes.core.foo': ( 'https://thigm85.github.io/core.html#foo',
                                                          'https://github.com/thigm85/mlopsnotes/blob/master/mlopsnotes/core.py#L7')}}}